### ISSUE TITLE
Poor performance on Identify in arcgis experience

### ISSUE THREAD

**Issue by BDvirus** [Esri/arcgis-experience-builder-sdk-resources#114]
Hi,

I have 40 feature layers in webmap 
Identify taking very very long time.. and it's not networking related.

![image](https://user-images.githubusercontent.com/5331340/158261053-cf188143-0ff5-4f4b-99cf-8d87e650ec77.png)

**Comment by gavinr** [comment]
Hi @BDvirus, thank you for your question. This GitHub repository is for issues and questions specifically related to the sdk sample widgets and themes (https://github.com/Esri/arcgis-experience-builder-sdk-resources). Since your question is related to a general Experience Builder issue, I would suggest contacting Esri Technical Support via the link here: https://developers.arcgis.com/experience-builder/support/
