### ISSUE TITLE
react-data-grid dependency issue

### ISSUE THREAD

**Issue by yiweima** [Esri/arcgis-experience-builder-sdk-resources#31]
When I try to add the react-data-grid widget to the developer version (rc3), this error shows:
![image](https://user-images.githubusercontent.com/4950370/88019544-e44ca480-cade-11ea-8a61-47ba7722d41a.png)

It seems the import argument:
`import * as ReactDataGrid from "react-data-grid";` 
in the widget.tsx is trying to look for the react-data-grid package under "client" rather than widget's own directory.

**Comment by gavinr** [comment]
@yiweima I think the issue here is that you did not yet run `npm install` within the widget folder. This is different from the other sample widgets where the rest work out of the box, but this is actually the point of this sample to show how you can create a widget that has a third-party dependency installed via NPM.
